### ISSUE TITLE
Make a post for the Republic Day

### ISSUE THREAD

**Issue by ShaileshKumar007** [GDSC-CEC/HacktoberFest-2022-Graphic-Designing#27]
Make a post on Republic Day.
Your post should follow the guidelines of the repo.

**Comment by siyaa12** [comment]
Can I work on this issue ?

**Comment by ShaileshKumar007** [comment]
> Can I work on this issue ?

Great. I'm assigning this issue to you.

**Comment by snehasish-pathak** [comment]
**can you assign this issue to me ?**
